apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: jenkins-devops
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: jenkins-devops
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 90
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 95
